# Generated by Django 4.2.13 on 2026-04-17 17:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_identifier', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('purchase_order', 'Purchase Order')], max_length=20)),
                ('source_reference_id', models.IntegerField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_available', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('received_at', models.DateTimeField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_entries',
                'indexes': [models.Index(fields=['user', 'product'], name='stock_entri_user_id_ca54de_idx'), models.Index(fields=['stock_identifier'], name='stock_entri_stock_i_eebbc0_idx'), models.Index(fields=['received_at'], name='stock_entri_receive_3e88e0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(fields=('stock_identifier',), name='unique_stock_identifier'),
        ),
    ]
