# Generated by Django 4.2.13 on 2026-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockentry',
            name='unique_stock_identifier',
        ),
        migrations.RemoveIndex(
            model_name='stockentry',
            name='stock_entri_stock_i_eebbc0_idx',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='stock_identifier',
        ),
    ]
