export const ROUTES = {
  login: '/login',
  root: '/',
  dashboard: '/dashboard',
  products: '/products',
  productNew: '/products/new',
  productDetail: (id: number | string) => `/products/${id}`,
  productEdit: (id: number | string) => `/products/${id}/edit`,
  stockEntries: '/stock-entries',
  stockDetail: (id: number | string) => `/stock-details/${id}`,
  stockEntryNew: '/stock-entries/new',
  stockEntryDetail: (id: number | string) => `/stock-entries/${id}`,
  stockEntryEdit: (id: number | string) => `/stock-entries/${id}/edit`,
  purchaseOrders: '/purchase-orders',
  purchaseOrderNew: '/purchase-orders/new',
  purchaseOrderDetail: (id: number | string) => `/purchase-orders/${id}`,
  purchaseOrderEdit: (id: number | string) => `/purchase-orders/${id}/edit`,
  salesOrders: '/sales-orders',
  salesOrderNew: '/sales-orders/new',
  salesOrderDetail: (id: number | string) => `/sales-orders/${id}`,
  salesOrderEdit: (id: number | string) => `/sales-orders/${id}/edit`,
  financial: '/financial',
} as const;
