# Generated by Django 4.2.13 on 2026-04-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('unit', 'Unit/Count')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['user', 'sku'], name='products_user_id_4299ac_idx'), models.Index(fields=['user', 'is_active'], name='products_user_id_655716_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('user', 'sku'), name='unique_sku_per_user'),
        ),
    ]
